export const barAssetsConstants = {
  'Bières artisanales': require('~/assets/images/bar-assets/beer-mug.png'),
  'Cocktails originaux': require('~/assets/images/bar-assets/cocktail.png'),
  'Vin de qualité': require('~/assets/images/bar-assets/wine.png'),
  'Sans alcool (mais pas que du coca)': require('~/assets/images/bar-assets/noalcohol.png'),
  Spiritueux: require('~/assets/images/bar-assets/liquor.png'),
  'Baby-foot': require('~/assets/images/bar-assets/babyfoot.png'),
  'Terrasse au soleil': require('~/assets/images/bar-assets/table.png'),
  'Jeux de société': require('~/assets/images/bar-assets/societe.png'),
  'Déco agréable': require('~/assets/images/bar-assets/deco.png'),
  'Place assises nombreuses': require('~/assets/images/bar-assets/seats.png'),
  'Musique cool': require('~/assets/images/bar-assets/music.png'),
  Burger: require('~/assets/images/bar-assets/burger.png'),
  'Assiettes jambon/fromage': require('~/assets/images/bar-assets/cheese.png'),
  Hummus: require('~/assets/images/bar-assets/hummus.png'),
  Tapas: require('~/assets/images/bar-assets/tapas.png'),
};
